# fly.toml app configuration file generated for simple-note-app on 2025-05-22T15:29:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-note-app'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
